name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Set up JDK 17
          uses: actions/setup-java@v2
          with:
            java-version: '17'

        - name: Build Spring Application
          uses: ./gradlew build

        - name: Start Docker Container
          uses: docker-compose up -d
