name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    # Workflow OS 지정
    runs-on: ubuntu-latest

    steps:
    # github workflow는 기본적으로 코드 접근이 불가
    # 따라서, github workflow가 돌아가는 공간에 결과물을 클론하여 가져갈 수 있도록 하위의 단계 지정
    - name: Checkout
    # 코드를 클론해가는 github action에는 여러 버전이 존재하는데, 그 중 4번째 버전을 선택 (기본값이었음)
    - uses: actions/checkout@v4

    # Spring Build
    - name: Build with Gradle
    - run: |
        chmod +x ./gradlew
        ./gradlew clean build -x test
        echo "Success: Spring Build"
    
    - name: Build the Docker image
      run: | 
        docker build . --file Dockerfile --tag my-image-name:$(date +%s)
        echo "Success: Docker Build"
