name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Build Spring Application
          run: ./gradlew build

        - name: Build & Update Docker Container
          run: docker-compose build

        - name: Start Docker Container
          run: docker-compose up -d
